### This is the main way to configure the application (other than annotations).
### This file is in Yaml format but you can also configure spring boot using the traditional
### Java properties file format. 


spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password: 


server:
  port: 8080

spring:
  h2:
    console:
      enabled: true

spring.jpa:
    hibernate.ddl-auto: create-drop

    
